### ISSUE TITLE
DB fails to initialize in 40-munin-master-admin.sh 

### ISSUE THREAD

**Issue by johngrasty** [skylime/mi-core-munin#1]
I imported the image (core-monitor 14.2.2) from datasets.at. After provisions, I see that zone initialization failed with this line in 40-munin-master-admin.sh:

```
sudo -u www /opt/munin_master_admin/manage.py syncdb --noinput
```

The resulting error was:

```
django.db.utils.OperationalError: unable to open database file
```

I resolved it with these two commands in 40-munin-master-admin.sh preceding line 20:

```
mkdir /var/munin_master_admin_db
chown www:www /var/munin_master_admin_db
```

**Comment by drscream** [comment]
Thanks a lot for your report. The problem appear only if you're using the MIBE image without an delegate dataset. I've fixed the issue in the current master and will try my best to release a new version soon.

**Comment by johngrasty** [comment]
That makes perfect sense. I forgot to check that script. I run anything with persistent data with a delegated dataset, but I was just testing this image and didn't. 

Thanks!
